// src/content.ts
export const calendarContent = [
    { date: "1 december", text: "Vad sägs om lite pyssel till glöggen? <br />Vik en söt liten presentpåse!", link: "https://youtu.be/Jyke0kOq9qw?si=MPoDzgzxD1tiOPeD", image: "./src/assets/origami_giftbag.png" },
    { date: "2 december", text: "Här är ett roligt recept!", link: "", image: "" },
    { date: "3 december", text: "Rocky Road", link: "", image: "" },
    { date: "4 december", text: "Vörtbröd", link: "", image: "" },
    { date: "5 december", text: "Naturligt glutenfritt julbröd. <br />Det går utmärkt att skippa kryddorna om man bara vill ha ett gott, glutenfritt bröd. Det brukar vi göra. <br />Vi brukar byta ut en del av degvätskan mot lingonsylt också...", link: "https://kronjast.se/recept/glutenfritt-julbrod/", image: "./src/assets/glutenfree_bread.png" },
    { date: "6 december", text: "Pepparkakssnittar", link: "", image: "" },
    { date: "7 december", text: "Paketinslagning", link: "", image: "" },
    { date: "8 december", text: "Pyssel är aldrig fel. <br />Enkla och snygga julgranskulor av pappersremsor", link: "https://pin.it/66jNTt09o", image: "./src/assets/paper_bauble.png" },
    { date: "9 december", text: "Det är idag man ska lägga lutfisken i blöt. <br />Dessutom har Anna namnsdag, så det är ju en ganska viktig dag.<br /> Ta en pepparkaka också, vetja!", link: "https://www.ica.se/recept/lutfisk-med-senapssas-3451/", image: "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_65181/cf_259/lutfisk_med_senapssas.jpg" },
    { date: "10 december", text: "Förbered lite godis till jul. <br />Härliga saffranskolor.", link: "https://www.coop.se/recept/saffranskola/", image: "https://res.cloudinary.com/coopsverige/image/upload/f_auto,fl_progressive,q_90,g_center,h_800,w_800/v1665473257/cloud/260002.jpg" },
    { date: "11 december", text: "Det är bara ett par dagar kvar, så nu börjar det bli dags för lussebullar", link: "https://www.coop.se/recept/lussebullar-grundrecept/", image: "https://res.cloudinary.com/coopsverige/image/upload/f_auto,fl_progressive,q_90,g_center,h_800,w_800/v1601545714/409312.jpg" },
    { date: "12 december", text: "Ingen lucia utan pepparkakor! <br />Men det är faktiskt inte fusk att köpa färdiga", link: "https://www.coop.se/recept/tant-harriets-pepparkakor/", image: "https://res.cloudinary.com/coopsverige/image/upload/f_auto,fl_progressive,q_90,g_center,h_800,w_800/v1432635770/32244.jpg" },
    { date: "13 december", text: "Lucia! Har du kommit ihåg att köpa ljus? <br />Fika och sjung idag, ta en paus från alla förberedelser.", link: "", image: "" },
    { date: "14 december", text: "Pärla snöflingor att hänga i granen eller fönstret", link: "https://rito.se/content/399-gratis-monster-pa-perle-snefnug", image: "https://rito.se/img/cms/opskriftsbilleder/kit-rito-0120%20perle%20snefnug/0-0-1.jpg" },
    { date: "15 december", text: "Kolla julgransbelysningen! <br />Det är ju inte kul om den inte funkar på julafton", link: "", image: "" },
    { date: "16 december", text: "Skippa pysslet idag och drick en mugg glögg istället.<br /> Köp färdig eller gör egen, vilket du tycker känns rimligast (jag köper min färdig)", link: "", image: "" },
    { date: "17 december", text: "Sill? <br />Det vet ju alla att om det inte är sill på bordet så är det ingen högtid.<br /> Det är sen gammalt", link: "", image: "" },
    { date: "18 december", text: "Julrim?<br /> Inte för mig, men många tycker att det är skoj.<br /> Här finns lite idéer", link: "", image: "" },
    { date: "19 december", text: "Vi behöver mer kola!<br /> Pepparkakskola är gott", link: "", image: "" },
    { date: "20 december", text: "Ska det komma gäster i jul?<br /> Kolla att gardiner och dukar är strukna så behöver inte mamma och svärmor slå ner på just DET.<br /> Sjunk sen ner i soffan och läs en bra bok eller somna till Netflix", link: "", image: "" },
    { date: "21 december", text: "Sista lugna kvällen att slå in julklappar.<br /> Här finns lite tips på olika sätt att variera inslagningen", link: "", image: "" },
    { date: "22 december", text: "Ärligt talat, nu blir det snart julmat i flera dagar, så ta en paus.<br /> Tacos är ypperlig pausmat", link: "", image: "" },
    { date: "23 december", text: "Jag griljerar aldrig skinkan förrän kvällen före julafton.<br /> Vill man inte ha skinka kan man griljera kalkon, blomkål eller kålrot, men för mig är det knäckemackan med nygriljerad skinka som gör det till jul", link: "https://www.coop.se/recept/griljerad-julskinka/", image: "https://res.cloudinary.com/coopsverige/image/upload/f_auto,fl_progressive,q_90,g_center,h_800,w_800/v1541664422/353524.jpg" },
    { date: "24 december", text: "Idag är det julafton, njut av allt du gjort under månaden!", link: "", image: "" },
];
